[package]
name = "cyan_backend"
version = "0.1.0"
edition = "2024"
[lib]
name = "cyan_backend"        # the Rust-side name of the library
path = "src/lib.rs"
crate-type = ["staticlib", "cdylib"]

[dependencies]
bytemuck = "1.23.1"
rkyv = "0.8.10"
xaeroid = "0.4.0"
rusted-ring = "0.5.1"
xaeroflux = "0.8.1-m5"
once_cell = "1.21.3"
